apiVersion: v1
kind: ConfigMap
metadata:
  name: rac-config-files
data:
  config.json: |
   {
  "authConfig": {
    "tenant": "{{ .Values.configMap.authConfig.tenant }}",
    "loginApiUrl": "{{ .Values.configMap.authConfig.loginApiUrl }}",
    "restApiUrl": "{{ .Values.configMap.authConfig.restApiUrl }}",
    "ssoFlag": {{ .Values.configMap.authConfig.ssoFlag }},
    "userIdleTime": {{ .Values.configMap.authConfig.userIdleTime }},
    "userIdleTimeOut": {{ .Values.configMap.authConfig.userIdleTimeOut }},
    "tokenExpFirstWarningMinutes": {{ .Values.configMap.authConfig.tokenExpFirstWarningMinutes }},
    "tokenExpSecondWarningMinutes": {{ .Values.configMap.authConfig.tokenExpSecondWarningMinutes }},
    "auth": {
      "issuer": "{{ .Values.configMap.authConfig.auth.issuer }}",
      "clientId": "{{ .Values.configMap.authConfig.auth.clientId }}",
      "redirectUri": "{{ .Values.configMap.authConfig.auth.redirectUri }}",
      "dummyClientSecret": "{{ .Values.configMap.authConfig.auth.dummyClientSecret }}",
      "logoutUrl": "{{ .Values.configMap.authConfig.auth.logoutUrl }}",
      "idpLogoutUrl": "{{ .Values.configMap.authConfig.auth.idpLogoutUrl }}",
      "requireHttps": {{ .Values.configMap.authConfig.auth.requireHttps }},
      "idpApiKey": "{{ .Values.configMap.authConfig.auth.idpApiKey }}",
      "interceptUrls": {{ .Values.configMap.authConfig.auth.interceptUrls | toJson }},
      "responseType": "{{ .Values.configMap.authConfig.auth.responseType }}",
      "autoRefresh": {{ .Values.configMap.authConfig.auth.autoRefresh }},
      "listenToToken": "{{ .Values.configMap.authConfig.auth.listenToToken }}"
    }
  }
}
