apiVersion: litmuchaos.io/v1alpha1
kind: LinuxFault
metadata:
  name: cf-app-network-latency
  labels:
    name: app-network-latency
spec:
  networkChaos/inputs:
    duration: 30s
    cfDeploymentPlatform: vSphere
    app: cf-app
    organization: dev-org
    space: dev-space
    networkLatency: "1000"
    jitter: "200"