apiVersion: litmuchaos.io/v1alpha1
kind: LinuxFault
metadata:
  name: redis-cache-expire
  labels:
    name: cache-expire
spec:
  redisChaos/inputs:
    duration: 30s
    expiration: 30s
    key: ""
    database: 1
    expiryOption: ""
    rampTime: ""