apiVersion: litmuchaos.io/v1alpha1
kind: K8sFault
metadata:
  name: redis-cache-penetration
      env:
        - name: TOTAL_CHAOS_DURATION
          value: "60" # in seconds
        ## Period to wait before and after injection of chaos in sec
        - name: RAMP_TIME
          value: ""
        - name: ADDRESS
          value: ""
        - name: REQUEST_COUNT
          value: "1000"
        - name: SECRET_FILE_PATH
          value: ""