---
# Block TCP connections to specific hostnames from a Lambda function
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: lambda-block-tcp-connection
spec:
  engineState: "active"
  chaosServiceAccount: litmus-admin
  experiments:
    - name: lambda-block-tcp-connection
      spec:
        components:
          env:
            - name: TARGET_HOSTNAMES
              value: 'example.com,api.example.com'