apiVersion: litmuchaos.io/v1alpha1
kind: LinuxFault
metadata:
  name: cf-app-network-duplication
  labels:
    name: app-network-duplication
spec:
  cfAppNetworkChaos/inputs:
    duration: 30s
    cfDeploymentPlatform: vSphere
    app: cf-app
    organization: dev-org
    space: dev-space
    packetDuplicationPercentage: '50'