# it inject the chaos for the egress traffic for specific ports
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
spec:
  engineState: "active"
  annotationCheck: "false"
  appinfo:
    appns: "default"
    applabel: "app=nginx"
    appkind: "deployment"
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-network-corruption
      spec:
        components:
          env:
            # supports comma separated source ports
            - name: SOURCE_PORTS
              value: '80'
            # supports comma separated destination ports
            - name: DESTINATION_PORTS
              value: '8080,9000'
            - name: TOTAL_CHAOS_DURATION
              value: '60'